-- Use the database (ensure you run this after connecting)
USE online_voting_system;

-- Places table
CREATE TABLE Places (
    place_id INT PRIMARY KEY AUTO_INCREMENT,
    place_name VARCHAR(100) UNIQUE NOT NULL
);

-- Candidates table
CREATE TABLE Candidates (
    candidate_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    party_name VARCHAR(100) NOT NULL,
    symbol_url VARCHAR(255)
);

--  Admins table
CREATE TABLE Admins (
    admin_id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL
);
-- voters table
CREATE TABLE Voters (
    voter_id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    aadhar_number VARCHAR(12) UNIQUE NOT NULL, 
    password_hash VARCHAR(255) NOT NULL,
    place_id INT NOT NULL,
    has_voted BOOLEAN DEFAULT FALSE, 
    FOREIGN KEY (place_id) REFERENCES Places(place_id)
    -- ON DELETE RESTRICT is implicit by default
);

-- vote table
CREATE TABLE Votes (
    vote_id INT PRIMARY KEY AUTO_INCREMENT,
    voter_id INT UNIQUE NOT NULL, -- Ensures a voter can only vote once
    candidate_id INT NOT NULL,
    vote_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (voter_id) REFERENCES Voters(voter_id),
    FOREIGN KEY (candidate_id) REFERENCES Candidates(candidate_id)
);

INSERT INTO Places (place_name) VALUES
('Ernakulam'),
('Kollam'),
('Kozhikode'),
('Thrissur'),
('Kannur');

-- Sample data for Admins (total 3)
INSERT INTO Admins (username, password_hash) VALUES
('admin1', 'admin1_password'),
('admin2', 'admin2_password'),
('admin3', 'admin3_password');

-- Sample data for Candidates (total 4)
INSERT INTO Candidates (name, party_name, symbol_url) VALUES
('Suresh Gopi', 'BJP', 'images/bjp_symbol.jpg'),
('Ganesh Kumar', 'LDF', 'images/ldf_symbol.jpg'),
('Shafi Parambil', 'UDF', 'images/udf_symbol.jpg'),
('Joicy Kurian', 'OTH', 'images/oth_symbol.jpg');

-- Sample data for Voters (total 10)
-- Ensure place_id values correspond to the IDs generated by AUTO_INCREMENT for Places (1-5)
INSERT INTO Voters (name, aadhar_number, password_hash, place_id) VALUES
('Seethal S Kumar', '111111111111', 'seethal_password', 2),   -- Kollam
('Jina Bobby', '222222222222', 'jina_password', 4),   -- Thrissur
('Malavika S Menon', '333333333333', 'malavika_password', 1), -- Ernakulam
('Lidiya Geevarghese', '444444444444', 'lidiya_password', 2),   -- Kollam
('Hazel Nilson', '555555555555', 'hazel_password', 4), -- Thrissur
('Anna Mathews', '666666666666', 'anna_password', 4), -- Thrissur
('Sreelakshmi M', '777777777777', 'sree_password', 5),    -- Kannur
('Sana N', '888888888888', 'sana_password', 3),    -- Kozhikode
('Harsha Thomas', '999999999999', 'harsha_password', 2),    -- Kollam
('Aleena Sunny', '000000000000', 'aleena_password', 3);   -- Kozhikode